[virtualenvs]
in-project = true

[tool.poetry]
name = "ca-server"
version = "0.3.11"
description = "Quickly create Certificate Authorities (CAs) for your applications."
authors = ["shina-m <shina.ct@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.119.0"
jinja2 = "^3.1.6"
uvicorn = "^0.37.0"
python-multipart = "^0.0.20"
aiofiles = "^24.1.0"
requests = "^2.32.5"
fastapi-utils = "^0.8.0"
python-dotenv = "^1.1.1"
peewee = "^3.18.2"
bcrypt = "^4.3.0"
cryptography = "^45.0.7"
greenlet = "^3.2.4"
pydantic = "^2.11.9"
certifi = "2025.8.3"

[tool.group.dev.dependencies]

[build-system]
requires = ["poetry>=1.1"]
build-backend = "poetry.masonry.api"
